#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

default_to_zsh() {
  #zsh should be installed w/ packages
  chsh -s $(which zsh)
}

install_zsh_customs() {
  $(which zsh) -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" || true
  rsync -a $DOTFILES_ROOT/oh-my-zsh/custom/ ~/.oh-my-zsh/custom/
}

install_fzf() {
  if ! [ -e ~/.fzf ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
  fi
}

install_ranger() {
  if ! [ -e ~/.ranger ]; then
    git clone https://github.com/ranger/ranger ~/.ranger
    cd ~/.ranger
    sudo make install
    cd $DOTFILES_ROOT
  fi
}

install_zsh_customs
install_fzf
install_ranger
default_to_zsh

# symlink files
stow .

echo ''
echo 'All installed!'
echo 'run source ~/.zshrc'
